version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      retries: 5
      start_period: 30s

  urlshortener:
    container_name: urlshortener
    build:
      dockerfile: Dockerfile
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=3000
      - PG_MAX_ATTEMPTION = 5
      - PG_HOST = postgres
      - PG_PORT = 5432
      - PG_USER = admin
      - PG_PASSWORD = admin
      - PG_DATABASE = testDB
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
